### PR TITLE
Add informal sector, update earnings ability matrix and demographics

### PR DESCRIPTION
**Pull request by jdebacker**
This PR is adds the same features as in PR #17, but also adjusts the demographics files to avoid a resource constraint error in the transition path.

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker. Code looks great. I am just running tests on my machine right now.

**Comment by rickecon** [comment]
@jdebacker. Can you update your branch to include the most recent PRs to OG-IND?

**Comment by jdebacker** [comment]
@rickecon Just updated...

**Comment by rickecon** [comment]
@jdebacker. I ran the code on my machine and all the tests pass and the `run_og_ind.py` script runs. Below is the output. I am merging this PR.

**Output from pytest**
```
============================= test session starts ==============================
platform darwin -- Python 3.9.15, pytest-7.2.1, pluggy-1.0.0
rootdir: /Users/richardevans/Docs/Economics/OSE/OG-IND, configfile: pytest.ini
plugins: xdist-3.1.0, anyio-3.6.2, pep8-1.0.6
collected 24 items                                                             

ogind/tests/test_calibrate.py ....                                       [ 16%]
ogind/tests/test_demographics.py ...........                             [ 62%]
ogind/tests/test_income.py ........                                      [ 95%]
ogind/tests/test_run_example.py .                                        [100%]
================= 24 passed, 39 warnings in 988.71s (0:16:28) ==================

```

**Baseline steady-state equilibrium computation output**
```
GE loop errors =  [8.339856583106098e-13, 8.54837034491851e-13, -5.3859139370615594e-11, -3.283695537703579e-11, 0.0, 3.911426738056889e-11, 8.689576835863022e-14, 1.1331074967202426e-12, 1.1219913886861832e-12, 5.039545170060222e-13, 7.185640971130169e-13, 9.916165111256703e-13, 1.5659496269138096e-12, 3.5202951664814464e-12, 2.53332077537749e-13]
Iteration: 01  Distance:  1.5917209957162216e-10
SS debt =  1.5424423067221116 0.012221170205067617
IO:  (2, 2) , C:  (2,)
Foreign debt holdings =  0.40103499974774903
Foreign capital holdings =  4.536051591584416
resource constraint:  [-1.47946100e-11  5.40045786e-12]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  5.3734794391857577e-14
Maximum error in savings FOC =  1.270095140171179e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-IND/examples/OG-IND-Example/OUTPUT_BASELINE/SS/SS_vars.pkl
```

**Baseline transition path equilibrium computation output (38 min, 33 sec)**
```
Max absolute value resource constraint error: 4.1052610844083404e-07
Checking time path for violations of constraints.
Max Euler error, savings:  3.7696512578122565e-12
Max Euler error labor supply:  6.776801342311956e-13
Time path iteration complete.
It took 2312.99413394928 seconds to get that part done.
run time =  2312.994188785553
```

**Reform steady-state equilibrium computation output**
```
GE loop errors =  [-1.569577801063815e-14, -1.569577801063815e-14, 6.09734485124136e-13, 5.274669589994119e-13, 0.0, 9.903189379656396e-14, 8.625045122556685e-15, 1.0734468869344482e-14, 1.0255685189974884e-14, 5.873773689657469e-15, 6.598888102615774e-15, 7.979727989493313e-15, 1.259409243559162e-15, 8.909539772616881e-15]
Iteration: 01  Distance:  3.164135620181631e-13
SS debt =  1.5277256790739502 0.01210456654958633
IO:  (2, 2) , C:  (2,)
Foreign debt holdings =  0.39720867655922704
Foreign capital holdings =  4.333419942971252
resource constraint:  [ 1.53099755e-13 -5.74540415e-14]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  5.551115123125783e-14
Maximum error in savings FOC =  1.2256862191861728e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-IND/examples/OG-IND-Example/OUTPUT_REFORM/SS/SS_vars.pkl
```

**Reform transition path equilibrium computation output (33 min, 43 sec)**
```
Maximum debt ratio:  1.0044638587277117
w diff:  6.632936710992965e-07 -2.4166903234146275e-07
r diff:  9.753025727310405e-09 -3.26507650014185e-08
r_p diff:  9.753025727310405e-09 -3.265076499447961e-08
p_m diff:  1.1013091893996574e-07 -3.6086215704500546e-07
BQ diff:  3.084592972851796e-07 -3.804266161810954e-08
TR diff:  2.0758206542570434e-08 -5.442183065862416e-07
Iteration: 24
	Distance: 6.99401874199891e-06
Max absolute value resource constraint error: 2.5217876862826394e-06
Checking time path for violations of constraints.
Max Euler error, savings:  3.855360475313319e-12
Max Euler error labor supply:  7.287503933639528e-13
Time path iteration complete.
It took 2022.7644159793854 seconds to get that part done.
run time =  2022.7644720077515
Percentage changes in aggregates: Year                    Variable  2021  2022  2023  ...  2029  2030  2021-2030    SS
0                    GDP ($Y_t$) -1.27 -1.20 -1.17  ... -0.99 -0.98      -1.10 -0.95
1            Consumption ($C_t$) -1.33 -0.96 -1.18  ... -1.52 -1.53      -1.36 -1.71
2          Capital Stock ($K_t$) -3.45 -3.42 -3.33  ... -3.12 -3.09      -3.24 -3.16
3                  Labor ($L_t$) -0.06  0.01  0.04  ...  0.19  0.20       0.10  0.29
4     Real interest rate ($r_t$) -0.26 -0.27 -0.26  ... -0.33 -0.34      -0.29 -0.18
5                      Wage rate -1.21 -1.20 -1.21  ... -1.18 -1.17      -1.20 -1.24

[6 rows x 13 columns]
```

**Pull request merged**
